version: "3.9"

services:
  db:
    container_name: identity-db
    environment:
      - POSTGRES_PASSWORD=password
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      
  identityserver:
    container_name: identityserver
    build:
      context: ../
      dockerfile: src/SampleHouseInfo.Infrastructure.Identity/Dockerfile
    depends_on:
      - db
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet SampleHouseInfo.Infrastructure.Identity.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__PATH=/https/localhost.pfx
      - CONNECTIONSTRINGS__IDENTITY=Server=db;Port=5432;Database=identity;User Id=postgres;Password=password;
      - CONNECTIONSTRINGS__IDENTITYSERVER=Server=db;Port=5432;Database=identityserver;User Id=postgres;Password=password;
    ports:
      - "7000:7000"
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro

  api:
    container_name: api
    build:
      context: ../
      dockerfile: src/SampleHouseInfo.API/Dockerfile
    depends_on:
      - identityserver
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet SampleHouseInfo.API.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__PATH=/https/localhost.pfx 
      - AUTHENTICATION__AUTHORITY=https://identityserver:7000
      - AUTHENTICATION__AUDIENCE=RoomsApi
    ports:
      - "7001:7001"
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro

  consoleapp:
    container_name: console-client
    build:
      context: ../
      dockerfile: src/Clients/ConsoleClient/Dockerfile
    depends_on:
      - api
      - identityserver
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet ConsoleClient.dll"
    environment:
      - AUTHENTICATION__AUTHORITY=https://identityserver:7000
      - AUTHENTICATION__CLIENTID=console-client-id
      - AUTHENTICATION__CLIENTSECRET=secret
    volumes:
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro

  webapplication:
    container_name: web-app-client
    build:
      context: ../
      dockerfile: src/Clients/WebAppClient/Dockerfile
    depends_on:
      - api
      - identityserver
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet WebAppClient.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__PATH=/https/localhost.pfx 
      - AUTHENTICATION__AUTHORITY=https://identityserver:7000
      - AUTHENTICATION__CLIENTID=webapp-client-id
      - AUTHENTICATION__CLIENTSECRET=secret
    ports:
      - "7002:7002"
    volumes:
      - ./localhost.pfx:/https/localhost.pfx:ro
      - ./localhost.crt:/usr/local/share/ca-certificates/localhost.crt:ro

  singlepageapplication:
    container_name: spa-client
    build:
      context: ../
      dockerfile: src/Clients/SPAClient/Dockerfile
    depends_on:
      - api
      - identityserver
    ports:
      - "7003:7003"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db: